### ISSUE TITLE
Specify terminal-notifier as gem dependency

### ISSUE THREAD

**Issue by andrewhavens** [Springest/terminal-notifier-guard#25]
It sounds like the `terminal-notifier` gem is a dependency for this gem to work. Is there a reason that this isn't specified as a dependency in the gemspec? Maybe this part was just overlooked since the binary is no longer bundled with this gem. I recently ran into the issue where I needed to manually install the `terminal-notifier` gem which was very strange because that part didn't seem to be documented anywhere.

**Comment by outdooricon** [comment]
Personally I prefer to install it via brew instead...

**Comment by foxycoder** [comment]
Yeah the version from brew is a lot faster.

From the docs:

> This version depends on the official terminal-notifier. Install it with Homebrew or see the official Installation instructions.
>

```
$ brew install terminal-notifier
```
